### ISSUE TITLE
RobotScheduler and Picker interaction

### ISSUE THREAD

**Issue by TylerFoster23** [kkloberdanz/CS2820#2]
The Picker and RobotScheduler need to have interaction. First of all, please call the Picker.java class in your RobotScheduler, as this static picker will be necessary for interactions.

In my Picker.java class, I have implemented a method that locates a Shelf that the picker needs; I will then use a method called notifyRobot(Shelf s) to request that a robot bring that particular shelf to the picker station. When that robot arrives, I need them to set Picker.atStation to be equal to the Shelf that the Robot just arrived with. This will tell the picker that the robot has arrived with the Shelf; after the item transfer has occurred, I can then instruct the Robot to take the shelf away, and request another Shelf.

**Comment by kkloberdanz** [comment]
Hi Tyler, MockRobotScheduler has a static method "public static int moveShelf(Shelf A, Point p)" Where you tell the robot to move Shelf A to Point p. This will then be put into a queue where each tick will move each robot one step on the path in moving the shelf.

It returns 0 if successful, and -1 if all the robots are busy. Does this work for you?

**Comment by TylerFoster23** [comment]
Hey Kyle,


That will work fine. I will just call that method for the appropriate time in MockOrders' tick method. I'll have to work with the Floor a bit to figure out where points are located, but I can figure this out with Gary tomorrow.


Thank you for your work on this!


Tyler

________________________________

**Comment by TylerFoster23** [comment]
As part of your tick, can you also have a method that checks to see if there is a robot at Point (0,0), and if this is true, then set the Picker.atStation field to be equal to the Shelf that the robot is carrying? I will need this for the purposes of knowing when a robot has arrived. Then I will call the method after transfering the items back to the location where the shelf is to be stored.


Tyler

________________________________

**Comment by kkloberdanz** [comment]
Are we assuming that the picker station is at (0,0)? If this is the case, maybe we should set the picker station in floor as a final static variable, so we aren't hard coding things.

What do you think?

**Comment by TylerFoster23** [comment]
That sounds like a good idea, we can implement this tomorrow in our meeting.


Tyler

________________________________
